language: node_js
node_js:
  - '8'
before_install:
  - npm install --global npm
script:
  - npm run lint
  - npm run test
after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
