variables:
  coverageDirectory: coverage
  nodeVersion: 10.15.3
  reportsDirectory: reports
jobs:
  - job: root_linux
    displayName: Root on Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - checkout: self
      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: $(nodeVersion)
      - script: yarn install
        displayName: Install Node dependencies
      - script: mkdir --parents $(coverageDirectory) $(reportsDirectory)
        displayName: Setup
      - script: |
          yarn --silent lint-files
          yarn --silent lint-scripts --format junit --output-file $(reportsDirectory)/lint-scripts.xml
        displayName: Run static analysis
      - script: yarn --silent test-units --coverage --runInBand --reporters default jest-junit
        displayName: Run tests
        env:
          JEST_JUNIT_OUTPUT: $(reportsDirectory)/test-units.xml
      - script: yarn --silent codecov --token=$(codecovToken)
        displayName: Publish code coverage results
      - task: PublishPipelineArtifact@0
        displayName: Publish coverage artifact
        inputs:
          artifactName: coverage
          targetPath: $(coverageDirectory)
      - task: PublishPipelineArtifact@0
        displayName: Publish reports artifact
        inputs:
          artifactName: reports
          targetPath: $(reportsDirectory)
      - task: PublishTestResults@2
        displayName: Publish tests results
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '**/*.xml'
          searchFolder: $(System.DefaultWorkingDirectory)/$(workingDirectory)/$(reportsDirectory)
