parameters:
  displayName: ''
  os: ''
  vmImage: ''
jobs:
  - job: setup_${{ parameters.os }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: $(nodeVersion)
      - script: mkdir --parents $(coverageDirectory)/${{ parameters.os }} $(reportsDirectory)/${{ parameters.os }}
        displayName: Setup
