parameters:
  displayName: ''
  os: ''
  vmImage: ''
jobs:
  - job: static_analysis_${{ parameters.os }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - setup
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: $(nodeVersion)
      - script: npm install
        displayName: Install Node dependencies
      - download: current
        displayName: Download reports artifact
        artifact: reports
      - script: |
          npm run --silent lint-files
          npm run --silent lint-scripts -- --format junit --output-file $(reportsDirectory)/${{ parameters.os }}/lint-scripts.xml
        displayName: Run static analysis

      - script: ls -ahl reports
