parameters:
  displayName: ''
  os: ''
  vmImage: ''
jobs:
  - job: static_analysis_${{ parameters.os }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - setup
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      - name: reportsDirectory
      - value: static-analysis-${{ parameters.os }}
    steps:
      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: $(nodeVersion)
      - script: npm install
        displayName: Install Node dependencies
      - script: |
          npm run --silent lint-files
          npm run --silent lint-scripts -- --format junit --output-file $(reportsDirectory)/lint-scripts.xml
        displayName: Run static analysis
      - publish: $(reportsDirectory)
        displayName: Publish reports artifact
        artifact: static-analysis-${{ parameters.os }}
