parameters:
  displayName: ''
  os: ''
  vmImage: ''
jobs:
  - job: test_${{ parameters.os }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - static_analysis_${{ parameters.os }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      - name: args
        value:
      - ${{ if eq(parameters.os, 'linux') }}:
        value: --coverage
    steps:
      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: $(nodeVersion)
      - script: npm install
        displayName: Install Node dependencies
      - script: npm run --silent test-units -- $(args) --runInBand --reporters default jest-junit
        displayName: Run tests
        env:
          JEST_JUNIT_OUTPUT: $(reportsDirectory)/${{ parameters.os }}/test-units.xml
