variables:
  - name: NODE_VERSION
    value: '>=10.16.0'
stages:
  - stage: root
    displayName: Root
    jobs:
      - template: jobs/static-analysis.yml
        parameters:
          displayName: Static Analysis on Linux
          os: linux
          vmImage: ubuntu-16.04
      - template: jobs/static-analysis.yml
        parameters:
          displayName: Static Analysis on macOS
          os: macos
          vmImage: macOS-10.14
      - template: jobs/static-analysis.yml
        parameters:
          displayName: Static Analysis on Windows
          os: windows
          vmImage: windows-2019
      - template: jobs/test.yml
        parameters:
          displayName: Test on Linux
          os: linux
          vmImage: ubuntu-16.04
      - template: jobs/test.yml
        parameters:
          displayName: Test on macOS
          os: macos
          vmImage: macOS-10.14
      - template: jobs/test.yml
        parameters:
          displayName: Test on Windows
          os: windows
          vmImage: windows-2019
trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master
