name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Setup Node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12.13
      - name: Install Yarn
        run: npm install --global yarn@1.19
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: Lint files
        run: yarn --silent lint:files
      - name: Lint scripts
        run: yarn --silent lint:scripts
      - name: Lint types
        run: yarn --silent lint:types
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Setup Node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12.13
      - name: Install Yarn
        run: npm install --global yarn@1.19
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: Test units
        run: yarn --silent test:units --coverage --runInBand
      - name: Publish code coverage results
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
