name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.18
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Install Node dependencies
        run: yarn install --immutable --immutable-cache
      - name: Lint files, scripts, and types
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.18
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Install Node dependencies
        run: yarn install --immutable --immutable-cache
      - name: Test units
        run: yarn test:units --coverage --run-in-band
      - name: Publish code coverage report
        uses: codecov/codecov-action@v1.0.12
