name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.14
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Install Node dependencies
        run: yarn install --immutable --immutable-cache
      - name: Lint files, scripts, and types
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.14
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Install Node dependencies
        run: yarn install --immutable --immutable-cache
      - name: Test units
        run: yarn test:units --coverage --runInBand
      - name: Publish code coverage results
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
